version: '3.5'

services:
  kotlin-restful-api:
    container_name: "kotlin-restful-api"
    image: kotlin-restful-api:0.0.1
    ports:
      - 8080:8080
    environment:
      DATABASE_URL: jdbc:postgresql://kotlin-restful-api-postgres:5432/restful-api
      DATABASE_PASSWORD: kotlin
      DATABASE_USERNAME: kotlin
    depends_on:
      - kotlin-restful-api-postgres
  kotlin-restful-api-postgres:
    container_name: "kotlin-restful-api-postgres"
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: kotlin
      POSTGRES_USER: kotlin
      POSTGRES_DB: restful-api